feat: update the main visual
sciwork/swconf pull request #24
Opened 2023-08-17 06:22 UTC by chestercheng

2023-08-19 13:27 UTC, jack482653 requested changes
然後文章內的文字大小好像不太一樣 要再調整一下

2023-08-19 13:27 UTC, jack482653 commented on content/2023/components/DrawerLink.tsx
> +          'tw-px-8 tw-py-2 tw-text-2xl tw-font-medium tw-leading-loose tw-text-neutral-900 hover:tw-text-sky-600',
tw-text-neutral-900 好像需要再調低一點 不然看不太出來有沒有 active
還是乾脆就不要有 active 了？
<img width="304" alt="CleanShot 2023-08-19 at 21 03 09@2x" src="https://github.com/sciwork/swconf/assets/6816342/c2a0785c-a622-4294-b52f-7c336edacc6e">

2023-08-19 13:27 UTC, jack482653 commented on content/2023/components/Footer.tsx
> +    <footer className="tw-w-full tw-mt-24">
這個好像改 Article 比較合適 tw-pt-10 tw-pb-32

2023-08-19 13:27 UTC, jack482653 commented on content/2023/components/Logo.tsx
> +        'tw-text-black': variant === 'dark',
這邊原本設計是可以透過 variant 去改變 logo 字的顏色
以我們現在的需求應該是改 light 的那個文字顏色
然後有用到 logo 的地方
```
<Logo variant="light" />
```

2023-08-19 13:27 UTC, jack482653 commented on content/2023/components/NavLink.tsx
> +        'tw-font-yk tw-text-xl tw-leading-loose hover:tw-text-sky-600',
沒用到 isActive 的話可以把上面用不到的變數砍掉
然後把 `'use client';` 拿掉

2023-08-19 13:27 UTC, jack482653 commented on content/2023/components/Button.tsx
> +          'tw-bg-yellow-300 hover:tw-bg-yellow-400 tw-text-black tw-rounded-full':
然後這個 variant 還要叫 danger 嗎 好像有點怪XD
改叫 action 怎麼樣

2023-08-19 13:27 UTC, jack482653 commented on content/2023/contents/home.mdx
> +<div className="tablet:tw-flex tablet:tw-items-start">
文章和圖片的間距
<img width="386" alt="CleanShot 2023-08-19 at 21 23 08@2x" src="https://github.com/sciwork/swconf/assets/6816342/7487f66c-2e28-4dac-8f2f-43180e4ceb71">

2023-08-19 13:27 UTC, jack482653 commented on content/2023/contents/home.mdx
> +    <img src="https://live.staticflickr.com/65535/52838576141_6faeaeb37e_k.jpg" />
圖片間的間距
<img width="444" alt="CleanShot 2023-08-19 at 21 23 50@2x" src="https://github.com/sciwork/swconf/assets/6816342/90f74b15-a8b4-4432-945c-c6f4ba21b1e2">

2023-08-19 13:27 UTC, jack482653 commented on content/2023/contents/home.mdx
> +<div className="tablet:tw-flex tablet:tw-items-start">
圖片和文章的間距
看這兩個段落能不能調整成一樣的間距？
<img width="464" alt="CleanShot 2023-08-19 at 21 25 04@2x" src="https://github.com/sciwork/swconf/assets/6816342/6133599f-5c35-485b-ac59-a4c1c9baf021">

2023-08-19 14:22 UTC, cstnaya commented on content/2023/contents/home.mdx
> +<div className="tablet:tw-flex tablet:tw-items-start">
<img width="581" alt="image" src="https://github.com/sciwork/swconf/assets/26144676/49bf8644-a3eb-4699-9f75-f60099b7039c">

左邊的文章段落跟右邊的圖片頂部間距沒有相等 （左邊 1.5em 右邊 2em），看起來會有點怪

2023-08-20 08:30 UTC, jack482653 commented on content/2023/app/page.tsx
> +            className="tw-font-yk tw-text-3xl tw-w-fit tw-text-black tw-border-b-2 tw-border-sky-600 tablet:tw-tracking-widest"
已修正 df6cb4f

2023-08-20 10:26 UTC, jack482653 commented on content/2023/components/Banner.tsx
> +      <div className="tw-absolute tw-prose-lg tw-text-left tw-font-yk tw-text-black tw-leading-none tablet:tw-mr-80">
發現沒有比較好 先不要這樣改

2023-08-20 10:28 UTC, jack482653 commented on content/2023/components/Button.tsx
> +          'tw-bg-yellow-300 hover:tw-bg-yellow-400 tw-text-black tw-rounded-full':
已調整 212a23e

2023-08-20 10:37 UTC, jack482653 commented on content/2023/components/DrawerLink.tsx
> +          'tw-px-8 tw-py-2 tw-text-2xl tw-font-medium tw-leading-loose tw-text-neutral-900 hover:tw-text-sky-600',
已調整 0cf6c1c

2023-08-20 10:43 UTC, jack482653 commented on content/2023/components/Footer.tsx
> +    <footer className="tw-w-full tw-mt-24">
已調整 067a07e

2023-08-20 10:46 UTC, jack482653 commented on content/2023/components/Logo.tsx
> +        'tw-text-black': variant === 'dark',
已調整 c2b07d0

2023-08-20 10:47 UTC, jack482653 commented on content/2023/components/NavLink.tsx
> +        'tw-font-yk tw-text-xl tw-leading-loose hover:tw-text-sky-600',
已調整 f2ce527

2023-08-20 16:10 UTC, merged